export const AUTHORIZATION_IN_PROGRESS = 'AUTHORIZATION_IN_PROGRESS';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILRUE';
export const DEAUTHORIZE_USER = 'DEAUTHORIZE_USER';

export const REQUEST_CONTACTS_IN_PROGRESS = 'REQUEST_CONTACTS_IN_PROGRESS';
export const REQUEST_CONTACTS_SUCCESS = 'REQUEST_CONTACTS_SUCCESS';
export const REQUEST_CONTACTS_FAILURE = 'REQUEST_CONTACTS_FAILURE';

export const OPEN_CONTACT_FORM = 'OPEN_CONTACT_FORM';
export const CLOSE_CONTACT_FORM = 'CLOSE_CONTACT_FORM';

export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
